version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - default

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://kafka:9094,DOCKER://host.docker.internal:29092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094,DOCKER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - default

  spark-master:
    build: .
    container_name: spark-master
    environment:
      - SPARK_RPC_MESSAGE_MAXSIZE=2047
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - .:/jackpot
    networks:
      - default

  spark-worker-1:
    build: .
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_MESSAGE_MAXSIZE=2047
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - default

  spark-worker-2:
    build: .
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_MESSAGE_MAXSIZE=2047
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    networks:
      - default
  
  spark-submit:
    build: .
    container_name: spark-submit
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_MESSAGE_MAXSIZE=2047
    depends_on:
      - spark-master
    volumes:
      - ./stream:/stream
      - .:/jackpot
    networks:
      - default

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
      - "19042:9042"
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - .:/home
      - /cassandra-data:/var/lib/cassandra
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G
          cpus: "1.0"
    networks:
      - default

networks:
  default:
    driver: bridge
